version: '3.9'

services:
  postgainer:
    image: postgres:latest
    container_name: postgainer
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    user: "1001:1001"  # соответствует PUID=1001 и PGID=1001
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


 pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 5082:5050
    env_file:
      - .env.pg4
    # volumes:
    #   - /var/lib/pgadmin/ants:/var/lib/pgadmin
    depends_on:
      - postgainer

 fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.db
      - .env.yc
    depends_on:
      - postgainer
