"""empty message

Revision ID: 210c812aff5f
Revises: e2edcd3b6307
Create Date: 2025-04-14 16:16:56.774085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "210c812aff5f"
down_revision: Union[str, None] = "e2edcd3b6307"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала удалите foreign key constraints
    op.execute("DROP TABLE jewelers CASCADE;")
    op.drop_table("orders")
    op.drop_table("m2m_jewelers_clients")
    op.execute("DROP TABLE clients CASCADE;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('clients_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column(
            "client_avatar", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "phone_number", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="clients_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "m2m_jewelers_clients",
        sa.Column("jeweler_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("client_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("cover_letter", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name="m2m_jewelers_clients_client_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["jeweler_id"],
            ["jewelers.id"],
            name="m2m_jewelers_clients_jeweler_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "jeweler_id", "client_id", name="m2m_jewelers_clients_pkey"
        ),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column(
            "image_order_path",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "workload",
            postgresql.ENUM("repair", "production", "both_add", name="workload"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("compensation", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("jeweler_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("client_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name="orders_client_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["jeweler_id"], ["jewelers.id"], name="orders_jeweler_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="orders_pkey"),
    )
    op.create_table(
        "jewelers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=30), autoincrement=False, nullable=True),
        sa.Column(
            "workload",
            postgresql.ENUM("repair", "production", "both_add", name="workload"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "phone_number", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column(
            "adress", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="jewelers_pkey"),
    )
    # ### end Alembic commands ###
