"""create initial tables

Revision ID: 60519016b922
Revises: d9736a25c64c
Create Date: 2025-04-23 09:06:57.093860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "60519016b922"
down_revision: Union[str, None] = "d9736a25c64c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Удаляем foreign key constraints
    op.drop_constraint(
        "m2m_jewelers_clients_jeweler_id_fkey",
        "m2m_jewelers_clients",
        type_="foreignkey",
    )
    op.drop_constraint("orders_jeweler_id_fkey", "orders", type_="foreignkey")

    # Просто добавляем postgresql_force_drop=True
    op.drop_table("m2m_jewelers_clients")
    op.drop_table(
        "orders",
    )
    op.drop_table(
        "jewelers",
    )
    op.drop_table(
        "clients",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "m2m_jewelers_clients",
        sa.Column("jeweler_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("client_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("cover_letter", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name="m2m_jewelers_clients_client_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["jeweler_id"],
            ["jewelers.id"],
            name="m2m_jewelers_clients_jeweler_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "jeweler_id", "client_id", name="m2m_jewelers_clients_pkey"
        ),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column(
            "order_avatar_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "workload",
            postgresql.ENUM(
                "repair", "production", "production_and_repair", name="workload"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("compensation", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("jeweler_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text(
                "timezone('utc'::text, (now() + '1 day'::interval))"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("client_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name="orders_client_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["jeweler_id"], ["jewelers.id"], name="orders_jeweler_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="orders_pkey"),
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "client_avatar_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "phone_number", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="clients_pkey"),
    )
    op.create_table(
        "jewelers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=30), autoincrement=False, nullable=True),
        sa.Column(
            "workload",
            postgresql.ENUM(
                "repair", "production", "production_and_repair", name="workload"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "portfolio", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "jeweler_avatar_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "phone_number", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column(
            "address", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="jewelers_pkey"),
    )
    # ### end Alembic commands ###
