"""change db

Revision ID: a8ae2a41d519
Revises: 210c812aff5f
Create Date: 2025-04-14 22:57:18.040283

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8ae2a41d519"
down_revision: Union[str, None] = "210c812aff5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "m2m_jewelers_clients" in tables:
        op.drop_constraint(
            "m2m_jewelers_clients_jeweler_id_fkey",
            "m2m_jewelers_clients",
            type_="foreignkey",
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
