"""empty message

Revision ID: d9736a25c64c
Revises: 056ca0c7052e
Create Date: 2025-04-17 13:11:27.579743

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9736a25c64c"
down_revision: Union[str, None] = "056ca0c7052e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jewelers", "email", existing_type=sa.VARCHAR(length=30), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jewelers", "email", existing_type=sa.VARCHAR(length=30), nullable=False
    )
    # ### end Alembic commands ###
