"""empty message

Revision ID: d9736a25c64c
Revises: 056ca0c7052e
Create Date: 2025-04-17 13:11:27.579743

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9736a25c64c"
down_revision: Union[str, None] = "056ca0c7052e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Удаляем foreign key constraints
    op.drop_constraint(
        "m2m_jewelers_clients_jeweler_id_fkey",
        "m2m_jewelers_clients",
        type_="foreignkey",
    )
    op.drop_constraint("orders_jeweler_id_fkey", "orders", type_="foreignkey")

    # Просто добавляем postgresql_force_drop=True
    op.drop_table(
        "m2m_jewelers_clients",
    )
    op.drop_table(
        "orders",
    )
    op.drop_table(
        "jewelers",
    )
    op.drop_table(
        "clients",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Заполняем NULL-значения (пример для email)
    op.execute("UPDATE jewelers SET email = '' WHERE email IS NULL")
    # ИЛИ для уникальных email:
    op.execute(
        "UPDATE jewelers SET email = 'user_' || id || '@example.com' WHERE email IS NULL"
    )

    op.alter_column(
        "jewelers", "email", existing_type=sa.VARCHAR(length=30), nullable=False
    )
    # ### end Alembic commands ###
